name = "vite-react2"
main = "api/_worker.js"
compatibility_date = "2025-01-27"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
# API routes обрабатываются Worker'ом первыми
run_worker_first = ["/api/*"]
